# Generated by Django 5.0.6 on 2024-11-18 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubc_voc_website', '0002_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('published', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('D', 'Default'), ('T', 'Tentative'), ('C', 'Cancelled')], default='D', max_length=1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('use_signup', models.BooleanField(default=False)),
                ('signup_question', models.CharField(max_length=256, null=True)),
                ('max_participants', models.IntegerField(null=True)),
                ('interested_start', models.DateTimeField(null=True)),
                ('interested_end', models.DateTimeField(null=True)),
                ('committed_start', models.DateTimeField(null=True)),
                ('committed_end', models.DateTimeField(null=True)),
                ('use_pretrip', models.BooleanField(default=False)),
                ('pretrip_time', models.DateTimeField()),
                ('pretrip_location', models.CharField(max_length=128)),
                ('drivers_required', models.BooleanField(default=False)),
                ('organizers', models.ManyToManyField(related_name='organized_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'Interested'), ('C', 'Committed'), ('G', 'Going')], default='I', max_length=1)),
                ('can_drive', models.BooleanField(default=False)),
                ('signup_answer', models.TextField(max_length=256, null=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
