# Generated by Django 5.0.6 on 2024-12-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('N', 'No'), ('T', 'Tentative'), ('C', 'Cancelled')], default='N', max_length=1),
        ),
    ]
