# Generated by Django 5.0.6 on 2025-01-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pretrip_time',
            field=models.DateTimeField(null=True),
        ),
    ]
