# Generated by Django 5.0.6 on 2025-01-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_triptag_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsignup',
            name='car_spots',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
