# Generated by Django 5.0.6 on 2025-02-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_tripsignup_car_spots_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='in_clubroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='pretrip_in_clubroom',
            field=models.BooleanField(default=False),
        ),
    ]
