# Generated by Django 5.0.6 on 2025-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_in_clubroom_trip_pretrip_in_clubroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='pretrip_in_clubroom',
        ),
        migrations.AlterField(
            model_name='trip',
            name='pretrip_location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
