# Generated by Django 5.0.6 on 2025-03-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triptag',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
