# Generated by Django 5.0.6 on 2025-10-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_alter_triptag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripsignup',
            name='type',
            field=models.CharField(choices=[('interested', 'Interested'), ('committed', 'Committed'), ('going', 'Going')], default='interested', max_length=10),
        ),
    ]
