# Generated by Django 5.2.8 on 2025-11-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_alter_tripsignup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='use_pretrip',
            field=models.BooleanField(default=True),
        ),
    ]
