# Generated by Django 5.2.8 on 2026-01-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_trip_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='signup_question',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
