# Generated by Django 5.2.8 on 2026-01-05 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_alter_trip_signup_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsignup',
            name='signup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tripsignup',
            name='type',
            field=models.IntegerField(choices=[(1, 'Interested'), (2, 'Committed'), (3, 'Going'), (4, 'No Longer Interested'), (5, 'Bailed From Committed'), (6, 'No Longer Going')], default=1),
        ),
    ]
