# Generated by Django 5.2.8 on 2026-01-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_tripsignup_signup_time_alter_tripsignup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='going_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='going_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
