# Generated by Django 5.2.10 on 2026-01-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_trip_going_end_trip_going_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='members_only_info',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
