# Generated by Django 5.0.6 on 2024-06-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_rename_firstname_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='acc',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trip_org_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vocene',
            field=models.BooleanField(default=True),
        ),
    ]
