# Generated by Django 5.0.6 on 2024-06-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_alter_profile_birthdate_alter_profile_blurb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='startdate',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='membership',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
