# Generated by Django 5.0.6 on 2024-08-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_rename_enddate_membership_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='membership.membership')),
                ('full_name', models.TextField(max_length=256)),
                ('student_number', models.TextField(max_length=8)),
                ('guardian_name', models.TextField(max_length=256)),
                ('signature', models.ImageField(upload_to='')),
                ('paper_waiver', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
