# Generated by Django 5.0.6 on 2025-02-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_alter_exec_user_alter_membership_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='blurb',
            new_name='bio',
        ),
    ]
