# Generated by Django 5.0.6 on 2024-06-06 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubc_voc_website', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('pronouns', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('student_number', models.CharField(max_length=8)),
                ('birthdate', models.DateField()),
                ('blurb', models.TextField()),
                ('acc', models.BooleanField()),
                ('vocene', models.BooleanField()),
                ('trip_org_email', models.BooleanField()),
            ],
        ),
    ]
