# Generated by Django 5.0.6 on 2024-06-06 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('ubc_voc_website', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exec',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('exec_role', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('type', models.CharField(choices=[('R', 'Regular'), ('A', 'Associate'), ('H', 'Honorary')], default='R', max_length=1)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PSG',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
