# Generated by Django 5.0.6 on 2024-06-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
