# Generated by Django 5.0.6 on 2024-08-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_waiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiver',
            name='signature',
            field=models.ImageField(upload_to='signatures/'),
        ),
    ]
