# Generated by Django 5.0.6 on 2024-11-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_alter_profile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Associate', 'Associate'), ('Honorary', 'Honorary')], default='Regular', max_length=10),
        ),
    ]
