# Generated by Django 5.0.6 on 2024-11-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_alter_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('R', 'Regular'), ('A', 'Associate'), ('H', 'Honorary')], default='R', max_length=1),
        ),
    ]
