# Generated by Django 5.0.6 on 2025-10-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_rename_blurb_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('R', 'Regular'), ('A', 'Associate'), ('H', 'Active Honorary'), ('I', 'Inactive Honourary')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
