# Generated by Django 5.2.8 on 2025-11-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_alter_membership_type_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emergency_info',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
