# Generated by Django 5.2.8 on 2026-01-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0025_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=32),
        ),
    ]
