# Generated by Django 5.2.8 on 2026-01-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0027_membership_unique_membership_user_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_info',
            field=models.TextField(blank=True, default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='inreach_address',
            field=models.TextField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
    ]
