# Generated by Django 5.2.8 on 2026-01-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0028_alter_profile_bio_alter_profile_emergency_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exec',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
