# Generated by Django 5.2.8 on 2026-01-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0029_exec_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emergency_info',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='inreach_address',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
