# Generated by Django 5.2.8 on 2026-01-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0030_alter_profile_emergency_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
