# Generated by Django 5.0.6 on 2025-05-05 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0013_alter_watermark_image'),
        ('trips', '0011_alter_triptag_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripGallery',
            fields=[
                ('gallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='photologue.gallery')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='trips.trip')),
            ],
            bases=('photologue.gallery',),
        ),
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('gallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='photologue.gallery')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('photologue.gallery',),
        ),
    ]
