# Generated by Django 5.0.6 on 2025-06-09 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_gearhour_start_time_alter_cancelledgearhour_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('deposit', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('deposit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.IntegerField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField()),
                ('extensions', models.IntegerField()),
                ('notes', models.TextField(null=True)),
                ('returned', models.BooleanField()),
                ('lost', models.BooleanField(default=False)),
                ('books', models.ManyToManyField(to='gear.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GearRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.IntegerField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField()),
                ('extensions', models.IntegerField()),
                ('notes', models.TextField(null=True)),
                ('returned', models.BooleanField()),
                ('lost', models.BooleanField(default=False)),
                ('gear', models.ManyToManyField(to='gear.gear')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
