# Generated by Django 5.2.10 on 2026-01-22 00:09

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripreports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Trip Report Categories',
            },
        ),
        migrations.AddField(
            model_name='tripreport',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='tripreports.tripreportcategory'),
        ),
    ]
