# Generated by Django 5.0.6 on 2025-09-04 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripreports', '0002_comment'),
        ('trips', '0011_alter_triptag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_report', to='trips.trip'),
        ),
    ]
