# Generated by Django 5.0.6 on 2025-03-19 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0011_alter_triptag_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1)),
                ('privacy', models.CharField(choices=[('PR', 'Private'), ('PU', 'Public')], default='PR', max_length=2)),
                ('content', models.TextField()),
                ('authors', models.ManyToManyField(related_name='written_trip_reports', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='trips.trip')),
            ],
        ),
    ]
