# Generated by Django 5.0.6 on 2025-04-14 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearhour',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='cancelledgearhour',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gearhour',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gearhour',
            name='start_date',
            field=models.DateField(),
        ),
    ]
