# Generated by Django 5.2.8 on 2026-01-12 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_gearhour_start_time_alter_cancelledgearhour_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Gear'), (2, 'Library')], default=1)),
                ('deposit', models.IntegerField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('extensions', models.IntegerField(default=0)),
                ('what', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('lost', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
