# Generated by Django 5.0.6 on 2025-06-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_book_gear_bookrental_gearrental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrental',
            name='extensions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookrental',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookrental',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gearrental',
            name='extensions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gearrental',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gearrental',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
