# Generated by Django 5.0.6 on 2025-07-02 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_alter_bookrental_extensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrental',
            name='returned',
        ),
        migrations.RemoveField(
            model_name='gearrental',
            name='returned',
        ),
    ]
