# Generated by Django 5.2.8 on 2025-12-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0006_alter_bookrental_notes_alter_bookrental_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrental',
            name='what',
            field=models.TextField(default='book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gearrental',
            name='what',
            field=models.TextField(default='gear'),
            preserve_default=False,
        ),
    ]
