# Generated by Django 5.2.8 on 2026-01-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0008_alter_bookrental_qm_alter_gearrental_qm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrental',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gearrental',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
