# Generated by Django 5.0.6 on 2025-01-19 20:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
