# Generated by Django 5.0.6 on 2025-01-29 07:59

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_triptag_trip_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptag',
            name='colour',
            field=colorfield.fields.ColorField(default='#808080', image_field=None, max_length=25, samples=None),
        ),
    ]
