# Generated by Django 5.0.6 on 2025-02-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_remove_trip_pretrip_in_clubroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField(default=60)),
            ],
        ),
    ]
